// Generated by MasonBundleBuilder
import 'package:mason/mason.dart';

final runnerScriptBundle = MasonBundle.fromJson({
  'files': [
    {
      'path': 'runner.dart',
      'data':
          'Ly8vIEdlbmVyYXRlZCBieSBtY3BfZGFydF9jbGkKbGlicmFyeTsKCmltcG9ydCAnZGFydDppbyc7CmltcG9ydCAncGFja2FnZTpsb2dnaW5nL2xvZ2dpbmcuZGFydCcgYXMgbG9nZ2luZzsKaW1wb3J0ICdwYWNrYWdlOm1jcF9kYXJ0L21jcF9kYXJ0LmRhcnQnOwovLyBpZ25vcmU6IHVyaV9kb2VzX25vdF9leGlzdAppbXBvcnQgJ3BhY2thZ2U6e3twYWNrYWdlTmFtZX19L21jcC9tY3AuZGFydCcgYXMgdXNlcl9jb2RlOwppbXBvcnQgJ3BhY2thZ2U6YXJncy9hcmdzLmRhcnQnOwoKdm9pZCBtYWluKExpc3Q8U3RyaW5nPiBhcmdzKSBhc3luYyB7CiAgZmluYWwgcGFyc2VyID0gQXJnUGFyc2VyKCkKICAgIC4uYWRkT3B0aW9uKCd0cmFuc3BvcnQnLCBhbGxvd2VkOiBbJ3N0ZGlvJywgJ2h0dHAnXSwgZGVmYXVsdHNUbzogJ3N0ZGlvJykKICAgIC4uYWRkT3B0aW9uKCdob3N0JywgZGVmYXVsdHNUbzogJzAuMC4wLjAnKQogICAgLi5hZGRPcHRpb24oJ3BvcnQnLCBkZWZhdWx0c1RvOiAnMzAwMCcpOwoKICBmaW5hbCByZXN1bHRzID0gcGFyc2VyLnBhcnNlKGFyZ3MpOwogIGZpbmFsIHRyYW5zcG9ydCA9IHJlc3VsdHNbJ3RyYW5zcG9ydCddIGFzIFN0cmluZzsKCiAgaWYgKHRyYW5zcG9ydCA9PSAnc3RkaW8nKSB7CiAgICBmaW5hbCBzZXJ2ZXIgPSB1c2VyX2NvZGUuY3JlYXRlTWNwU2VydmVyKCk7CiAgICBmaW5hbCB0cmFuc3BvcnQgPSBTdGRpb1NlcnZlclRyYW5zcG9ydCgpOwogICAgYXdhaXQgc2VydmVyLmNvbm5lY3QodHJhbnNwb3J0KTsKICB9IGVsc2UgaWYgKHRyYW5zcG9ydCA9PSAnaHR0cCcpIHsKICAgIHZhciBob3N0ID0gcmVzdWx0c1snaG9zdCddIGFzIFN0cmluZzsKICAgIHZhciBwb3J0ID0gaW50LnBhcnNlKHJlc3VsdHNbJ3BvcnQnXSBhcyBTdHJpbmcpOwoKICAgIC8vIFNldHVwIHNpbXBsZSBsb2dnaW5nIGZvciBIVFRQCiAgICBsb2dnaW5nLkxvZ2dlci5yb290LmxldmVsID0gbG9nZ2luZy5MZXZlbC5BTEw7CiAgICBsb2dnaW5nLkxvZ2dlci5yb290Lm9uUmVjb3JkLmxpc3RlbigocmVjb3JkKSB7CiAgICAgIHN0ZGVyci53cml0ZWxuKCcke3JlY29yZC5sZXZlbC5uYW1lfTogJHtyZWNvcmQudGltZX06ICR7cmVjb3JkLm1lc3NhZ2V9Jyk7CiAgICB9KTsKICAgIGZpbmFsIGxvZ2dlciA9IGxvZ2dpbmcuTG9nZ2VyKCdNY3BIdHRwU2VydmVyJyk7CgogICAgZmluYWwgc2VydmVyID0gU3RyZWFtYWJsZU1jcFNlcnZlcigKICAgICAgc2VydmVyRmFjdG9yeTogKHNlc3Npb25JZCkgPT4gdXNlcl9jb2RlLmNyZWF0ZU1jcFNlcnZlcigpLAogICAgICBob3N0OiBob3N0LAogICAgICBwb3J0OiBwb3J0LAogICAgICBldmVudFN0b3JlOiBJbk1lbW9yeUV2ZW50U3RvcmUoKSwKICAgICk7CiAgICBhd2FpdCBzZXJ2ZXIuc3RhcnQoKTsKICAgIGxvZ2dlci5pbmZvKCdTZXJ2ZXIgcnVubmluZyBhdCBodHRwOi8vJGhvc3Q6JHBvcnQvbWNwJyk7CiAgfQp9Cg==',
      'type': 'text',
    },
  ],
  'hooks': [],
  'name': 'runner_script',
  'description': 'A brick to generate the MCP server runner script.',
  'version': '0.1.0',
  'environment': {
    'mason': '>=0.1.0-dev.1 <0.1.0',
  },
  'vars': {
    'packageName': {
      'type': 'string',
      'description': 'The name of the package.',
    },
  },
});
