/// Generated by mcp_dart_cli
library;

import 'dart:io';
import 'package:logging/logging.dart' as logging;
import 'package:mcp_dart/mcp_dart.dart';
// ignore: uri_does_not_exist
import 'package:{{packageName}}/mcp/mcp.dart' as user_code;
import 'package:args/args.dart';

void main(List<String> args) async {
  final parser = ArgParser()
    ..addOption('transport', allowed: ['stdio', 'http'], defaultsTo: 'stdio')
    ..addOption('host', defaultsTo: '0.0.0.0')
    ..addOption('port', defaultsTo: '3000');

  final results = parser.parse(args);
  final transport = results['transport'] as String;

  if (transport == 'stdio') {
    final server = user_code.createMcpServer();
    final transport = StdioServerTransport();
    await server.connect(transport);
  } else if (transport == 'http') {
    var host = results['host'] as String;
    var port = int.parse(results['port'] as String);

    // Setup simple logging for HTTP
    logging.Logger.root.level = logging.Level.ALL;
    logging.Logger.root.onRecord.listen((record) {
      stderr.writeln('${record.level.name}: ${record.time}: ${record.message}');
    });
    final logger = logging.Logger('McpHttpServer');

    final server = StreamableMcpServer(
      serverFactory: (sessionId) => user_code.createMcpServer(),
      host: host,
      port: port,
      eventStore: InMemoryEventStore(),
    );
    await server.start();
    logger.info('Server running at http://$host:$port/mcp');
  }
}
